name: Push on main
on:
  push:
    branches: [ main ]
jobs:
  push:
    runs-on: ubuntu-latest
    environment: Development
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package YAML files
        run: |
          mkdir artifacts
          cp src/test/resources/*.yaml artifacts/
          zip -r my_project_artifact.zip artifacts
          echo "Artifact created: my_project_artifact.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_project_artifact
          path: my_project_artifact.zip

      - uses: microcks/import-github-action@v1
        with:
          specificationFiles: 'artifacts/*:true'
          microcksURL: 'https://microcks.dbank.engineering/api/'
          keycloakClientId:  'microcks-serviceaccount'
          keycloakClientSecret:  'ab54d329-e435-41ae-a900-ec6b3fe15c54'