name: Push on main
on:
  push:
    branches: [ main ]
jobs:
  push:
    runs-on: ubuntu-latest
    environment: Development
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package YAML files
        run: |
          mkdir artifacts
          cp src/main/*/*.yaml artifacts/

      - name: List YAML files and set environment variable
        run: |
          SPEC_FILES=""
          for file in $(find artifacts -type f -name "*.yaml"); do
            filename=$(basename $file)
            SPEC_FILES="$SPEC_FILES,artifacts/${filename}:true"
          done
          # Removing leading comma
          SPEC_FILES=${SPEC_FILES#,}
          echo "SPEC_FILES=${SPEC_FILES}" >> $GITHUB_ENV

      - name: Import YAML files into Microcks
        uses: microcks/import-github-action@v1
        with:
          specificationFiles: ${{ env.SPEC_FILES }}
          microcksURL: 'https://microcks.dbank.engineering/api/'
          keycloakClientId:  'microcks-serviceaccount'
          keycloakClientSecret:  'ab54d329-e435-41ae-a900-ec6b3fe15c54'
