name: Push on main
on:
  push:
    branches: [ main ]
jobs:
  push:
    runs-on: ubuntu-latest
    environment: Development
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: List YAML files and set environment variable
        run: |
          SPEC_FILES=""
          for file in $(find src/main/*/*.yaml -type f -name "*.yaml"); do
            SPEC_FILES="$SPEC_FILES,$file:true"
          done
          # Removing leading comma
          SPEC_FILES=${SPEC_FILES#,}
          echo "SPEC_FILES=${SPEC_FILES}" >> $GITHUB_ENV

      - name: Import YAML files into Microcks
        uses: microcks/import-github-action@v1
        with:
          specificationFiles: ${{ env.SPEC_FILES }}
          microcksURL: 'https://microcks.dbank.engineering/api/'
          keycloakClientId:  ${{ secrets.MICROCKS_SERVICE_ACCOUNT }}
          keycloakClientSecret:  ${{ secrets.MICROCKS_SERVICE_ACCOUNT_CREDENTIALS }}
